EXPERIMENTAL_SETTINGS = {}


from Hyperparameters.experimental_settings.S15W1_light_noBeta import FIXED_HYPERPARAMETERS, TUNING_HYPERPARAMETERS, HARDWARE_PARAMETERS, DENSITY_PARAMETERS
EXPERIMENTAL_SETTINGS.update(
    {
        'S15W1_light_noBeta' : {
            'FIXED_HYPERPARAMETERS' : FIXED_HYPERPARAMETERS,
            'TUNING_HYPERPARAMETERS' : TUNING_HYPERPARAMETERS,
            'HARDWARE_PARAMETERS' : HARDWARE_PARAMETERS,
            'DENSITY_PARAMETERS' : DENSITY_PARAMETERS,
        }
    }
)

from Hyperparameters.experimental_settings.S5W1_saniity_check import FIXED_HYPERPARAMETERS, TUNING_HYPERPARAMETERS, HARDWARE_PARAMETERS, DENSITY_PARAMETERS
EXPERIMENTAL_SETTINGS.update(
    {
        'S5W1_sanity_check' : {
            'FIXED_HYPERPARAMETERS' : FIXED_HYPERPARAMETERS,
            'TUNING_HYPERPARAMETERS' : TUNING_HYPERPARAMETERS,
            'HARDWARE_PARAMETERS' : HARDWARE_PARAMETERS,
            'DENSITY_PARAMETERS' : DENSITY_PARAMETERS,
        }
    }
)


from Hyperparameters.experimental_settings.S15G1W1_light_noBeta_baseline import FIXED_HYPERPARAMETERS, TUNING_HYPERPARAMETERS, HARDWARE_PARAMETERS, DENSITY_PARAMETERS
EXPERIMENTAL_SETTINGS.update(
    {
        'S15G1W1_light_noBeta_baseline' : {
            'FIXED_HYPERPARAMETERS' : FIXED_HYPERPARAMETERS,
            'TUNING_HYPERPARAMETERS' : TUNING_HYPERPARAMETERS,
            'HARDWARE_PARAMETERS' : HARDWARE_PARAMETERS,
            'DENSITY_PARAMETERS' : DENSITY_PARAMETERS,
        }
    }
)

from Hyperparameters.experimental_settings.S15G2W1_light_noBeta_baseline import FIXED_HYPERPARAMETERS, TUNING_HYPERPARAMETERS, HARDWARE_PARAMETERS, DENSITY_PARAMETERS
EXPERIMENTAL_SETTINGS.update(
    {
        'S15G2W1_light_noBeta_baseline' : {
            'FIXED_HYPERPARAMETERS' : FIXED_HYPERPARAMETERS,
            'TUNING_HYPERPARAMETERS' : TUNING_HYPERPARAMETERS,
            'HARDWARE_PARAMETERS' : HARDWARE_PARAMETERS,
            'DENSITY_PARAMETERS' : DENSITY_PARAMETERS,
        }
    }
)

from Hyperparameters.experimental_settings.S15G3W1_light_noBeta_baseline import FIXED_HYPERPARAMETERS, TUNING_HYPERPARAMETERS, HARDWARE_PARAMETERS, DENSITY_PARAMETERS
EXPERIMENTAL_SETTINGS.update(
    {
        'S15G3W1_light_noBeta_baseline' : {
            'FIXED_HYPERPARAMETERS' : FIXED_HYPERPARAMETERS,
            'TUNING_HYPERPARAMETERS' : TUNING_HYPERPARAMETERS,
            'HARDWARE_PARAMETERS' : HARDWARE_PARAMETERS,
            'DENSITY_PARAMETERS' : DENSITY_PARAMETERS,
        }
    }
)


from Hyperparameters.experimental_settings.S15G1W1_light_noBeta_normalized import FIXED_HYPERPARAMETERS, TUNING_HYPERPARAMETERS, HARDWARE_PARAMETERS, DENSITY_PARAMETERS
EXPERIMENTAL_SETTINGS.update(
    {
        'S15G1W1_light_noBeta_normalized' : {
            'FIXED_HYPERPARAMETERS' : FIXED_HYPERPARAMETERS,
            'TUNING_HYPERPARAMETERS' : TUNING_HYPERPARAMETERS,
            'HARDWARE_PARAMETERS' : HARDWARE_PARAMETERS,
            'DENSITY_PARAMETERS' : DENSITY_PARAMETERS,
        }
    }
)




from Hyperparameters.experimental_settings.S15G2W1_light_noBeta_normalized import FIXED_HYPERPARAMETERS, TUNING_HYPERPARAMETERS, HARDWARE_PARAMETERS, DENSITY_PARAMETERS
EXPERIMENTAL_SETTINGS.update(
    {
        'S15G2W1_light_noBeta_normalized' : {
            'FIXED_HYPERPARAMETERS' : FIXED_HYPERPARAMETERS,
            'TUNING_HYPERPARAMETERS' : TUNING_HYPERPARAMETERS,
            'HARDWARE_PARAMETERS' : HARDWARE_PARAMETERS,
            'DENSITY_PARAMETERS' : DENSITY_PARAMETERS,
        }
    }
)




from Hyperparameters.experimental_settings.S15G3W1_light_noBeta_normalized import FIXED_HYPERPARAMETERS, TUNING_HYPERPARAMETERS, HARDWARE_PARAMETERS, DENSITY_PARAMETERS
EXPERIMENTAL_SETTINGS.update(
    {
        'S15G3W1_light_noBeta_normalized' : {
            'FIXED_HYPERPARAMETERS' : FIXED_HYPERPARAMETERS,
            'TUNING_HYPERPARAMETERS' : TUNING_HYPERPARAMETERS,
            'HARDWARE_PARAMETERS' : HARDWARE_PARAMETERS,
            'DENSITY_PARAMETERS' : DENSITY_PARAMETERS,
        }
    }
)



